feat: finaly maked project
KoTuK2306/coffeeHouse pull request #2
Opened 2022-04-20 18:30 UTC by KoTuK2306

2022-04-20 19:24 UTC, pavelsokolov21 requested changes

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/coffee.tsx
> +const makePathToImage = (path: string) => `${process.env.PUBLIC_URL}/images/coffee/${path}.png`;
почему этот файл `tsx`, если тут нет разметки?

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Footer/Footer.tsx
> +  { id: 1, title: "Главная", href: "#" },
тут `id == idx`. Зачем тогда нужно это поле?

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Footer/Footer.tsx
> +            <a key={id} href={href} className={classes.link}>
id (idx) использовать как ключ фигово, тк процесс ререндера может стать хуже. Лучше использовать более уникальные значения (тот же title)

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Footer/Footer.tsx
> +          <p className={classes.phone}>8(123)456-67-89</p>
`<a tel=..`

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Footer/Footer.tsx
> +          <p className={classes.mail}>katyusha.karachinskaya@yandex.ru</p>
`<a href="mailto...`

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Header/Header.tsx
> +  { id: 1, href: "#", title: "Главная" },
`id == idx`?

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Header/Header.tsx
> +const headerLinks = [
на самом деле, такие массивы лучше тоже типизировать явно типом

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/weekOffers.ts
> +    id: "one",
че? Почему такой id? Зачем?

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/weekOffers.ts
> +const icons = {
лишний объект

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/reasonsIcons.tsx
> +    <svg width="72" height="94" viewBox="0 0 72 94" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
почему одни иконки в паблике, а какие-то в тут?

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Menu/Menu.module.css
> +  margin-right: 35px;
есть свойство у флексовых/гридовых контейнеров `grid-gap`. С помощью него задаются отступы между элементами контейнера

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Menu/Menu.module.css
> +.chevronRotated {
ниже я видел просто класс `active`, а тут прям для чеврона. Я бы тут либо использовал BEM: `chevron_rotated`, либо просто `.chevron.rotated`

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Menu/Menu.tsx
> +  const lastCardIndex = currentPage;
тут что-то уже магическое. Я даже не знаю, как это комментировать

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Menu/Menu.tsx
> +            <p
это `button`

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Menu/Menu.tsx
> +  const slideSlider = (option: string) => {
`option` принимает не стринг, а ровно два параметра: `left | right`. Вынеси в union-type

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Menu/Menu.tsx
> +  const slideSlider = (option: string) => {
название функции тавталогично. Лучше тогда `shiftSlider`

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Menu/Menu.tsx
> +  const pageNumbers = [];
не совсем понимаю, зачем нам это? Для лишних перерисовок? Если это для того, чтобы была анимация, то лучше рассчитывать `transform: translateX(N px)`, где `N` нужно тебе подумать, как считать

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Menu/Menu.tsx
> +            <img src={`${process.env.PUBLIC_URL}/sliderChevron.svg`} alt="chevron" className={classes.chevron} />
ни в одном месте уже вижу такую конструкцию для public. У тебя уже есть функция, которая делают путь к паблику. Вынеси ее в утилку и реюзай

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Preview/Preview.module.css
> +.offferImage {
```suggestion
.offerImage {

```

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Preview/Preview.module.css
> +.offferImage:not(:first-child) {
```suggestion
.offerImage:not(:first-child) {

```

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Preview/Preview.tsx
> +import { weekOffers } from "./../../weekOffers";
странный импорт

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Preview/Preview.tsx
> +import { Link } from "react-scroll";
сначала бибки

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Preview/Preview.tsx
> +        <img className={classes.coffeeBeans} src={`${process.env.PUBLIC_URL}/coffeeBeans.png`} alt="cofeeBeans" />
```suggestion
        <img className={classes.coffeeBeans} src={`${process.env.PUBLIC_URL}/coffeeBeans.png`} alt="coffeeBeans" />

```

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/components/Preview/Preview.tsx
> +        <img className={classes.coffeeBeans} src={`${process.env.PUBLIC_URL}/coffeeBeans.png`} alt="cofeeBeans" />
это лучше задать через background, нежели через картинку

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/index.css
> +  --primaryFont: OpenSans, sans-serif;
600, 700 нормально отрабатывают?

2022-04-20 19:24 UTC, pavelsokolov21 commented on src/index.css
> +  --color1: #fff9d8;
тк тут 4 цвета всего, то можно и нормальные названия придумать вместо `color1`

2022-04-20 19:28 UTC, KoTuK2306 commented on src/index.css
> +  --primaryFont: OpenSans, sans-serif;
Чекни демку

2022-04-21 20:46 UTC, pavelsokolov21 requested changes

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Footer/Footer.tsx
> +          {linksChild.map(({ title, href, id }: Link) => (
Хорошая попытка типизации, но выглядит стремно. Лучше затипизируй интерфейсои `linksChild`

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Footer/Footer.tsx
> +const linksChild = [
Вот прям child? Просто links ну никак?)

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Footer/Footer.tsx
> +          <a href="telephone" className={classes.phone}>
https://www.elegantthemes.com/blog/wordpress/call-link-html-phone-number#:~:text=Adding%20an%20HTML%20Phone%20Number%20Call%20Link%20to%20your%20Website&text=Href%3Dtel%3A%20creates%20the%20call,the%20number%20it%20will%20call.

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Footer/Footer.tsx
> +          <a href="mail" className={classes.mail}>
https://www.tutorialspoint.com/html/html_email_links.htm

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Header/Header.module.css
> +* {
Выглядит как общий сброс настроек. Почему бы не использовать это тогда только в одном файле? Мб index.css или создать resets.css?

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Header/Header.module.css
> +  height: 120px;
Фиксировать высоту такое себе занятие для таких блоков. При масштабировании будут проблемы. Пусть высота будет зависеть от контента и просто задать паддинги

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Header/Header.module.css
> +  margin-left: 60px;
`grid-gap`

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Header/Header.tsx
> +interface linkTypes {
У тебя ведь есть уже такой интерфейс

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Header/Header.tsx
> +          {headerLinks.map(({ id, href, title }: Link) => (
Зачем типизация поверх другой типизации

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Menu/CoffeeCard/CoffeeCard.module.css
> +  margin-left: 80px;
`grid-gap`

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Menu/CoffeeCard/CoffeeCard.tsx
> +import { Coffee } from "./../../../interfaces/Coffee";
Кривой импорт

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Menu/Menu.module.css
> +.viewport {
Отступ

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Menu/Menu.module.css
> +.rotated {
Просто `rotated` мало о себе говорит. Я бы сделал либо `.chevron.rotated`, если юзать только для него, либо `.rotated180` для реюза, как ютилити класс

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Menu/Menu.module.css
> +  background-color: #e9aa7c;
Переменная

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Menu/Menu.tsx
> +  const slideSlider = (option: "right" | "left") => {
Ну Димка, вынеси этот тип в переменную. Лучше прям в этом файле, тк реюз вряд ли будет

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Menu/Menu.tsx
> +  const cardWidth = 335;
Переменная будет создаваться при каждом ререндере. Лучше создать ее вне компонента и капсом

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Menu/Menu.tsx
> +      setTranslate(translate - 335);
Юзай переменную

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Menu/Menu.tsx
> +          {coffeeImages.slice(0, pagesCount).map((card, index) => (
`card` не используется, на что должен возникать линтер. Для таких случаев пиши вместо обязательного параметра `_`

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Menu/Menu.module.css
> +  height: 638px;
Зачем хардкод высоты?

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Preview/Preview.module.css
> +  height: 1021px;
Зачем хардкод высоты

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Preview/Preview.module.css
> +.bigText {
title

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Preview/Preview.module.css
> +.smallText {
subtitle

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Reasons/Reasons.tsx
> +import classes from "./Reasons.module.css";
Стили в конце

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Reasons/Reasons.module.css
> +  margin-left: 125px;
`grid-gap`

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Reasons/Reasons.module.css
> +  height: 565px;
Зачем хардкод

2022-04-21 20:46 UTC, pavelsokolov21 commented on public/sliderChevron.svg
> +<svg width="17" height="15" viewBox="0 0 17 15" fill="none" xmlns="http://www.w3.org/2000/svg">
А если эта иконка вдруг не для слайдера понадобится? Название для иконок не привязывай к сущности

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/App.tsx
> +      <Header />
Предложение: можно создать layout, который будет содержать header и footer. А в него уже оборачивать начинку

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Footer/Footer.module.css
> +  height: 500px;
Зачем хардкод

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Footer/Footer.module.css
> +  height: 300px;
Хардкод

2022-04-21 20:46 UTC, pavelsokolov21 commented on src/components/Footer/Footer.module.css
> +}
`grid-gap`

2022-04-22 19:41 UTC, pavelsokolov21 requested changes

2022-04-22 19:41 UTC, pavelsokolov21 commented on src/App.tsx
> +      <Header />
layouts

2022-04-22 19:41 UTC, pavelsokolov21 commented on src/components/Preview/Preview.tsx
> +        <img className={classes.coffeeBeans} src={makePathToPublic("/coffeeBeans.png")} alt="cofeeBeans" />
это лучше вставить как бэкграунд к блоку, чем через картинку

2022-04-22 19:41 UTC, pavelsokolov21 commented on src/components/Preview/Preview.tsx
> +            <img className={classes.offerImage} key={id} src={icon} alt={`weekOffer${id}`} />
`alt` неясный. Во-первых, этот преффикс ненужен, тк `id` уже информативный, как я видел. Во-вторых, если прям нужен преффикс, то его стоит написать через дефис

2022-04-22 19:41 UTC, pavelsokolov21 commented on src/components/Slider/Slider.tsx
> +  children: ReactNode;
`FC` уже имеет типизацию для `children`. Этот интерфейс не нужен

2022-04-22 19:41 UTC, pavelsokolov21 commented on src/components/Slider/Slider.tsx
> +interface optionType {
```suggestion
type OptionType = "left"  | "right"

```

2022-04-22 19:41 UTC, pavelsokolov21 commented on src/components/Slider/Slider.tsx
> +  const shiftSlider = (option: optionType["option"]) => {
смотри про коммент про тип

2022-04-22 19:41 UTC, pavelsokolov21 commented on src/components/Slider/Slider.tsx
> +import { CARD_WIDTH } from "../../constants/cardWidth";
мне кажется, что эта константа локальная и не нужно её выносить в сурс-папку. Достаточно объявить её в этом файле до компонента, либо создать в этой папке файл с константами

2022-04-22 19:41 UTC, pavelsokolov21 commented on src/components/Slider/Slider.tsx
> +  const pagesCount = Children.toArray(children).length - 2;
`Children.count(children)` не работает?

2022-04-22 19:41 UTC, pavelsokolov21 commented on src/components/Slider/Slider.tsx
> +  const pagesCount = Children.toArray(children).length - 2;
https://reactjs.org/docs/react-api.html#reactchildrencount

2022-04-22 22:22 UTC, KoTuK2306 commented on src/components/Slider/Slider.tsx
> +  children: ReactNode;
Без него почему-то ругается IDE, даже компилить не хочет

2022-04-22 22:23 UTC, KoTuK2306 commented on src/components/Slider/Slider.tsx
> +  const pagesCount = Children.toArray(children).length - 2;
Работает не так как нужно

2022-04-23 12:35 UTC, pavelsokolov21 requested changes

2022-04-23 12:35 UTC, pavelsokolov21 commented on src/components/Menu/CoffeeCard/CoffeeCard.module.css
> +  letter-spacing: 0.05em;
Повтор

2022-04-23 12:35 UTC, pavelsokolov21 commented on src/components/Menu/CoffeeCard/CoffeeCard.module.css
> +  letter-spacing: 0.05em;
Я так смотрю, это значение повторяется везде. Наверно, его стоит в переменную вынести

2022-04-23 12:35 UTC, pavelsokolov21 commented on src/components/Header/Header.module.css
> +  padding: 50px 245px;
И тут ты пойман за жопу. У тебя несколько секций и ты копипастишь в каждую этот паддинг. Создай один ютилити класс/компонент-контейнер и реюзай

2022-04-23 12:35 UTC, pavelsokolov21 commented on src/components/Preview/Preview.module.css
> +.coffeeBeans {
Этот класс не используется

2022-04-23 12:37 UTC, KoTuK2306 commented on src/components/Header/Header.module.css
> +  padding: 50px 245px;
Поймали за жопу(

2022-04-24 21:09 UTC, pavelsokolov21 requested changes

2022-04-24 21:09 UTC, pavelsokolov21 commented on src/components/Footer/Footer.tsx
> +    <MainPadding className={classes.footer}>
А будет `MainMargin` или `MainColor`?) почему это просто не контейнер?

2022-04-24 21:09 UTC, pavelsokolov21 commented on src/components/Footer/Footer.tsx
> +    <MainPadding className={classes.footer}>
У тому же, у тебя рушится семантика и это стал просто div, а не секция или  футер. Сделай контейнер просто доп оберткой для контента

2022-04-24 21:09 UTC, pavelsokolov21 commented on src/components/Reasons/Reasons.module.css
> +  margin: 0 245px;
А вот и нашел место для `MainMargin`)

2022-04-24 21:09 UTC, pavelsokolov21 commented on src/components/Reasons/Reasons.tsx
> +      <div className={classes.content}>
А тут ты решил не использовать `MainPadding`, а сделал доп обертку. БиполярОчка

2022-04-25 18:38 UTC, pavelsokolov21 approved these changes

2022-04-25 18:40 UTC, merged